// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvdW7jiEuMirfylTNdRL9t6M4LBc-h5ls',
    appId: '1:356101455757:web:4b717fcf9b1ac46a2347c4',
    messagingSenderId: '356101455757',
    projectId: 'atelierpro3-sio2',
    authDomain: 'atelierpro3-sio2.firebaseapp.com',
    storageBucket: 'atelierpro3-sio2.firebasestorage.app',
    measurementId: 'G-56B7P1M1GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNQ--2gwQH6gRTIfReKPfHmSHCLGbeBcI',
    appId: '1:356101455757:android:fd03fa7ed696bf402347c4',
    messagingSenderId: '356101455757',
    projectId: 'atelierpro3-sio2',
    storageBucket: 'atelierpro3-sio2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd-Qd_3p-gqsoAy4OYobl7itq0XZx8J0s',
    appId: '1:356101455757:ios:97ad5a84fe58d7f62347c4',
    messagingSenderId: '356101455757',
    projectId: 'atelierpro3-sio2',
    storageBucket: 'atelierpro3-sio2.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjet3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd-Qd_3p-gqsoAy4OYobl7itq0XZx8J0s',
    appId: '1:356101455757:ios:97ad5a84fe58d7f62347c4',
    messagingSenderId: '356101455757',
    projectId: 'atelierpro3-sio2',
    storageBucket: 'atelierpro3-sio2.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjet3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvdW7jiEuMirfylTNdRL9t6M4LBc-h5ls',
    appId: '1:356101455757:web:3723f43560453dc82347c4',
    messagingSenderId: '356101455757',
    projectId: 'atelierpro3-sio2',
    authDomain: 'atelierpro3-sio2.firebaseapp.com',
    storageBucket: 'atelierpro3-sio2.firebasestorage.app',
    measurementId: 'G-0DXGJ29VWR',
  );
}
